### ISSUE TITLE
Right click on navigation panel

### ISSUE THREAD

**Issue by Rousan99** [MathInspector/MathInspector-Alpha-Test#1]
I am trying but clicking right click on the navigation panel , is not activating upper block in windows version. 
Can you help me out?

**Comment by MathInspector** [comment]
Fixed!  I have uploaded a new build which you can find from the same download link, it should have a version number 0.1.1 in the filename when you download it.

I did all of the development on Mac and just learned there are some differences with how windows handles the right click button.  I believe I have found all the places where right click is checked and updated the windows build.

Please let me know if you find any other bugs and I can put up a new build with fixes as they come in.

**Comment by Rousan99** [comment]
Thank you...now it's perfect. 
I am having another problem.
I plotted an array as you have shown in our 2nd video as a test. But it's showing a line instead points . Here is the image
![Screenshot (31)](https://user-images.githubusercontent.com/51227331/74356725-d5055480-4de4-11ea-8eeb-ae8be4fa8acd.png)

**Comment by MathInspector** [comment]
Ah yes, nice catch.  I had been messing around with the graph system to make it stable and get the alpha test out, and that got messed up.  Will fix this in an upcoming release once more bugs come in.  Thanks so much for testing

**Comment by Rousan99** [comment]
😅😅..got this while fooling around. It's truly remarkable. If you can please make it right quickly 😅.. I am testing to find some more errors.

**Comment by MathInspector** [comment]
ok fixed!  new build is up 0.1.2

turns out there were some subtle issue's you brought my attention to so a few other things also just got fixed for the graph as well
